name: filterlos_ich
description: "Das In-App-Ventil für Ausraster, Geistesblitze und ungefilterte Gedanken."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.3+3

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cryptography: ^2.9.0
  flutter_secure_storage: ^11.2.0
  file_picker: ^13.1.0
  speech_to_text: ^7.5.0
  local_auth: ^3.0.2
  path: ^1.9.1
  path_provider: ^2.1.6
  intl: ^0.20.3
  record: ^7.1.1
  audioplayers: ^6.8.1
  llm_llamacpp: ^0.7.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic/OpenDyslexic-Bold.otf
          weight: 700
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Regular.ttf
        - asset: assets/fonts/Noto_Sans/static/NotoSans-Bold.ttf
          weight: 700
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/Courier_Prime/CourierPrime-Regular.ttf
        - asset: assets/fonts/Courier_Prime/CourierPrime-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: Ubuntu Mono
      fonts:
        - asset: assets/fonts/Ubuntu/UbuntuMono-Regular.ttf
        - asset: assets/fonts/Ubuntu/UbuntuMono-Bold.ttf
          weight: 700
